import { arabicAreas } from "./area-translations.ts";
export type Locale = "en" | "ar";
export const messages = {
  photoLoading: ["Loading location photo…", "جارٍ تحميل صورة المكان…"],
  photoMissing: ["Location photo not yet available", "لا تتوفر صورة موثّقة للمكان بعد"],
  photoFailed: ["Photo could not load", "تعذر تحميل الصورة"],
  photoNeutral: ["VAELORA area profile · not a photograph of this place", "بطاقة المكان من فيلورا · ليست صورة لهذا المكان"],
  terrainUnknown: ["Terrain not documented", "التضاريس غير موثّقة"], terrainFlat: ["Flat", "مسطحة"], areaProfile: ["Activity area", "منطقة للنشاط الخارجي"], selectedArea: ["Selected on your map", "المكان المحدد على خريطتك"],
  photoCredit: ["Photo credit", "مصدر الصورة وحقوقها"], photoSource: ["Original photograph", "الصورة الأصلية"],
  photoChanges: ["Resized, WebP compressed and cropped for display. Photo adaptation retains the linked license.", "صُغّرت الصورة وضُغطت بصيغة WebP واقتُصّت للعرض. تظل النسخة المعدّلة خاضعة للرخصة المرتبطة."],
  photoHistorical: ["Reference photo, not a live view or evidence of current access or conditions.", "صورة مرجعية، وليست بثًا مباشرًا أو دليلًا على حالة المكان أو إمكانية الدخول حاليًا."],
  showOnMap: ["Select & show on map", "اختر واعرض على الخريطة"],
  showAll: ["Show all places", "عرض كل الأماكن"], partial: ["Some forecasts are incomplete. Only areas with usable conditions are shown.", "بعض التوقعات ناقصة. نعرض الأماكن التي تتوفر لها ظروف قابلة للتقييم فقط."], constraints: ["Your planning constraints", "شروط خطتك"], checkedHours: ["Forecast hours checked per outing", "ساعات التوقعات المفحوصة لكل نشاط"],
  brand: ["VAELORA", "فيلورا"], home: ["Home", "الرئيسية"], planner: ["Your planner", "خطّط لنشاطك"], map: ["Explore the map", "استكشف الخريطة"],
  tagline: ["OUTDOOR PLANNING · BUILT FOR JORDAN", "تخطيط ذكي لنشاطك الخارجي · من أجل الأردن"],
  headline: ["Find your place.\nMake your move.", "اختر مكانك.\nوانطلق."],
  intro: ["Your next run or walk, planned around the weather. Real places in Amman. Your best time to go.", "خطّط للجري أو المشي وفق الطقس. أماكن حقيقية في عمّان، وأوقات أنسب لنشاطك."],
  expansion: ["Built for Jordan · Starting with Greater Amman", "من أجل الأردن · البداية من عمّان الكبرى"],
  coverage: ["Currently optimized for Greater Amman. Other cities are not supported yet.", "التوصيات متاحة حاليًا لعمّان الكبرى. المدن الأخرى غير مدعومة بعد."],
  ask: ["Ask VAELORA", "اسأل فيلورا"], askHelp: ["Your words. One useful plan.", "صف ما تفضّله، ودع فيلورا يقترح خطتك."], prompt: ["Describe your outing", "صف نشاطك الذي تخطّط له"],
  placeholder: ["A flat, low-wind run tomorrow after 6 PM…", "أريد الجري غدًا بعد السادسة مساءً في مكان مسطح ورياح خفيفة…"], send: ["Find my plan", "اقترح خطتي"],
  suggestion1: ["Where should I run tonight near me?", "أين يمكنني الجري الليلة قريبًا مني؟"], suggestion2: ["A flat run tomorrow after 6 PM.", "الجري في مكان مسطح غدًا بعد السادسة مساءً."], suggestion3: ["A 45-minute walk tomorrow morning.", "المشي لمدة 45 دقيقة صباح الغد."],
  aiRule: ["AI understands intent. Verified data and the engine decide. Your prompt is sent to the AI provider; avoid personal or sensitive information.", "الذكاء الاصطناعي يفهم طلبك. البيانات المراجعة والمحرك يحددان التوصية. يُرسل نص طلبك إلى مزوّد الذكاء الاصطناعي؛ تجنّب المعلومات الشخصية أو الحساسة."],
  near: ["Best place near me now", "أنسب مكان قريب مني الآن"], nearHelp: ["Use my location · approximate distance", "استخدم موقعي · مسافة تقريبية"], run: ["Plan my run", "خطّط للجري"], walk: ["Plan my walk", "خطّط للمشي"], runHelp: ["Find your stride", "اختَر وقتك وانطلق"], walkHelp: ["Make time to move", "خصص وقتًا للحركة"],
  activity: ["Activity", "النشاط"], running: ["Running", "الجري"], walking: ["Walking", "المشي"], time: ["When", "متى؟"], duration: ["Time to move", "مدة النشاط"], minutes: ["min", "دقيقة"],
  now: ["Now", "الآن"], tonight: ["Tonight", "الليلة"], "tomorrow-morning": ["Tomorrow morning", "صباح الغد"], "tomorrow-evening": ["Tomorrow evening", "مساء الغد"],
  durationNote: ["30–60 minute outings check a full forecast hour; 90 minutes checks two. Starts are whole-hour, not route or travel-time estimates.", "لنشاط 30–60 دقيقة نفحص ساعة توقعات كاملة، ولـ90 دقيقة نفحص ساعتين. البداية على رأس الساعة؛ ليست تقديرًا لمدة مسار أو تنقّل."],
  preferences: ["Make it yours", "حسب تفضيلاتك"], optional: ["Optional", "اختياري"], flat: ["Flatter terrain", "أرض مسطحة"], paved: ["Paved surface", "سطح معبّد"], park: ["Park", "حديقة"], lowWind: ["Lower wind", "رياح أخف"], avoidHeat: ["Avoid heat", "تجنب الحر"],
  find: ["Find My Best Spots", "اعثر على أنسب الأماكن"], checking: ["Checking places and conditions…", "نتحقق من الأماكن والظروف…"], choose: ["A little planning. A better outing.", "تخطيط بسيط. نشاط أكثر متعة."],
  location: ["Distance reference", "مرجع المسافة"], noLocation: ["No location selected", "لم يُحدد موقع"], manual: ["Or choose an area near you", "أو اختَر منطقة قريبة منك"], useLocation: ["Use my location", "استخدم موقعي"], located: ["Location ready · kept in this browser only", "تم تحديد الموقع · يبقى في هذا المتصفح فقط"], locating: ["Finding your location…", "نحدد موقعك…"], geoDenied: ["Location unavailable. Choose a reference area below, or plan without distance.", "تعذر تحديد موقعك. اختَر منطقة مرجعية أدناه، أو تابع دون مسافة."], clearLocation: ["Clear location", "مسح الموقع"], manualNote: ["Distances are from the selected area, not your exact position.", "المسافات محسوبة من المنطقة المختارة، وليس من موقعك الدقيق."], far: ["You are outside our current local coverage. These are Amman options, not nearby recommendations.", "أنت خارج نطاق تغطيتنا المحلية الحالية. هذه خيارات في عمّان، وليست توصيات قريبة منك."],
  results: ["Your outdoor plan", "خطتك للنشاط الخارجي"], top: ["Best option to consider", "خيارك المقترح"], alternative: ["Strong alternative", "بديل مناسب"], closest: ["Next closest Top Match", "أقرب بديل من الخيارات المتكافئة"], ties: ["These options share the leading match band. Small weather differences are not a quality ranking.", "هذه الخيارات ضمن فئة التوصيات الأولى. فروق الطقس الصغيرة لا تعني تفوق مكان على الآخر."], nearbyOrder: ["Closest first within the leading match band.", "الأقرب أولًا ضمن فئة التوصيات الأولى."], bestTime: ["Best time", "أنسب وقت"], approx: ["Approx. straight-line distance", "مسافة جغرافية تقريبية بخط مستقيم"], km: ["km", "كم"], kmh: ["km/h", "كم/س"], feels: ["Feels like", "المحسوسة"], wind: ["Wind", "الرياح"], rain: ["Rain chance", "احتمال المطر"],
  preferred: ["Comfortable conditions", "ظروف مريحة"], acceptable: ["Acceptable conditions", "ظروف مقبولة"], poor: ["Less suitable", "أقل ملاءمة"], unavailable: ["Unavailable", "غير متاح"], why: ["Why it fits", "لماذا يناسبك؟"], fitWhy: ["Reviewed activity fit and your constraints match. This window has the best available conditions for this area.", "خصائص المكان المراجعة تناسب النشاط وتفضيلاتك. هذه النافذة تقدم أفضل الظروف المتاحة لهذا المكان."], limitedWhy: ["This activity has documented limitations here. Review the area notes before choosing this window.", "لهذا النشاط قيود موثقة هنا. راجع ملاحظات المكان قبل اختيار هذه النافذة."],
  details: ["Area details & evidence", "تفاصيل المكان والأدلة"], terrain: ["Terrain", "التضاريس"], surface: ["Surface", "السطح"], environment: ["Environment", "البيئة"], evidence: ["Evidence status", "حالة الأدلة"], source: ["Evidence source", "مصدر الدليل"], sourceNote: ["Original sources may use another language.", "قد تكون المصادر الأصلية بلغة أخرى."], suitable: ["Suitable", "مناسب"], limited: ["Limited fit", "ملاءمة محدودة"], unknown: ["Not verified", "غير موثّق"], verified: ["Verified", "متحقق منه"], supported: ["Evidence-supported", "مدعوم بالأدلة"], rolling: ["Rolling", "متفاوت الانحدار"], hilly: ["Hilly", "تلال"], track: ["Track", "مضمار"], gravel: ["Gravel", "حصى"], dirt: ["Dirt", "ترابي"], urban: ["Urban", "حضري"], woodland: ["Woodland", "أشجار وغابات"], "open-space": ["Open space", "مساحة مفتوحة"],
  save: ["Save area", "حفظ المكان"], saved: ["Saved area", "مكان محفوظ"], favorites: ["Saved places", "أماكنك المحفوظة"], noneSaved: ["Save an area from your results for later.", "احفظ مكانًا من النتائج للرجوع إليه لاحقًا."],
  conditions: ["When outside feels better", "متى تكون الظروف أفضل؟"], hourly: ["Your hourly outlook", "الظروف ساعة بساعة"], best: ["Recommended", "موصى به"], hourlyNote: ["Hourly forecasts, Jordan time. Missing data is unavailable; good weather is not a safety guarantee.", "توقعات كل ساعة بتوقيت الأردن. البيانات الناقصة غير متاحة؛ الطقس الجيد ليس ضمانًا للسلامة."],
  trace: ["How VAELORA reached this plan", "كيف توصّل فيلورا إلى هذه الخطة؟"], traceNote: ["Factual actions only — no hidden reasoning.", "خطوات فعلية فقط، دون عرض التفكير الداخلي."],
  "activity-detected": ["Activity detected", "تحديد النشاط"], "constraints-extracted": ["Constraints applied", "تطبيق التفضيلات"], "eligible-locations-found": ["Areas filtered", "تصفية الأماكن"], "weather-retrieved": ["Weather checked", "فحص الطقس"], "suitability-calculated": ["Suitability calculated", "حساب الملاءمة"], "best-time-evaluated": ["Best time evaluated", "تقييم أنسب وقت"], "matches-returned": ["Matches returned", "إرجاع الخيارات"], "constraints-need-clarification": ["Clarification needed", "نحتاج توضيحًا"],
  error: ["We couldn’t complete this plan. Please try again or adjust your choices.", "تعذر إكمال الخطة. حاول مجددًا أو عدّل خياراتك."], empty: ["No match for this time and these constraints. Try tomorrow or remove an optional preference. Nothing was silently relaxed.", "لا توجد خيارات لهذا الوقت والتفضيلات. جرّب الغد أو أزل تفضيلًا اختياريًا. لم نخفف أي شرط دون إخبارك."], weatherError: ["Weather is unavailable. We won’t guess a recommendation.", "الطقس غير متاح. لن نخمن توصية دون بيانات."], aiError: ["Ask VAELORA is unavailable. You can still explore the dashboard.", "اسأل ڤيلورا غير متاح حاليًا. يمكنك متابعة استكشاف لوحة النشاط."], clarification: ["Please specify running or walking, today or tomorrow, and a clear time. Only reviewed Amman areas and supported preferences are available.", "حدد الجري أو المشي، اليوم أو غدًا، ووقتًا واضحًا. ندعم أماكن عمّان المراجعة والتفضيلات المتاحة فقط."], retry: ["Adjust my plan", "تعديل خطتي"],
  disclaimer: ["Weather suitability is not a safety guarantee. Check opening hours and access. Routes, travel time, accessibility, shade and air quality are not verified.", "ملاءمة الطقس ليست ضمانًا للسلامة. تحقق من ساعات الفتح والدخول. المسارات ووقت التنقل وإمكانية الوصول والظل وجودة الهواء غير متحقق منها."],
  mapCaption: ["Reviewed area coordinates · no routes", "إحداثيات أماكن مراجعة · دون مسارات"], show: ["Show area", "عرض المكان"], zoomIn: ["Zoom in", "تكبير"], zoomOut: ["Zoom out", "تصغير"], attribution: ["Map attribution", "مصادر الخريطة"], mapLoading: ["Loading map…", "تحميل الخريطة…"], mapError: ["Map unavailable. Your recommendations remain available.", "الخريطة غير متاحة. توصياتك ما زالت متاحة."],
  built: ["Built for Jordan. Made for your next move.", "من أجل الأردن. لنشاطك القادم."], dataCredit: ["Forecasts: Open-Meteo · Map: © OpenStreetMap contributors", "التوقعات: Open-Meteo · الخريطة: © مساهمو OpenStreetMap"], pause: ["Pause motion", "إيقاف الحركة"], resume: ["Resume motion", "تشغيل الحركة"], more: ["All Top Matches", "كل الخيارات المتكافئة"],
} as const;
export type MessageKey = keyof typeof messages;
export function t(locale: Locale, key: MessageKey): string { return messages[key][locale === "ar" ? 1 : 0]; }
export function label(locale: Locale, value: string): string { return Object.hasOwn(messages, value) ? t(locale, value as MessageKey) : t(locale, "unavailable"); }
export function areaName(locale: Locale, area: { id: string; name: string }): string { return locale === "ar" ? arabicAreas[area.id]?.name ?? t(locale, "unavailable") : area.name; }
export function areaDescription(locale: Locale, area: { id: string; description: string }): string { return locale === "ar" ? arabicAreas[area.id]?.description ?? t(locale, "unavailable") : area.description; }
export function numberText(locale: Locale, value: number | null | undefined, digits = 0): string { return value == null || !Number.isFinite(value) ? t(locale, "unavailable") : new Intl.NumberFormat(locale === "ar" ? "ar-JO" : "en-JO", { maximumFractionDigits: digits }).format(value); }
export function windowText(start: string, end: string): string { return `${start.slice(11, 16)}–${end.slice(11, 16)}`; }
/** Unknown terrain is not an assertion about the area's separate evidence status. */
export function terrainText(locale: Locale, terrain: string): string { return terrain === "unknown" ? t(locale,"terrainUnknown") : `${t(locale,"terrain")}: ${terrain === "flat" ? t(locale,"terrainFlat") : label(locale,terrain)}`; }
