import test from "node:test";
import assert from "node:assert/strict";
import {createPlanningPipeline,createPlanningHandler,parsePlanningRequest} from "../../src/server/recommendations/planning.ts";
import {createOpenMeteoAdapter} from "../../src/server/weather/open-meteo.ts";
import {parseSavedAreas} from "../../src/lib/saved-areas.ts";
import {localActivityAnswer} from "../../src/domain/tracking/summary.ts";
const now=new Date("2026-09-15T00:00:00Z");
const times=["2026-09-15","2026-09-16","2026-09-17"].flatMap(d=>Array.from({length:24},(_,h)=>`${d}T${String(h).padStart(2,"0")}:00`));
function payload(){return {latitude:32,longitude:35.8,elevation:900,timezone:"Asia/Amman",utc_offset_seconds:10800,hourly_units:{time:"iso8601",temperature_2m:"°C",apparent_temperature:"°C",relative_humidity_2m:"%",wind_speed_10m:"km/h",precipitation_probability:"%",uv_index:""},hourly:{time:times,temperature_2m:times.map(()=>25),apparent_temperature:times.map(()=>25),relative_humidity_2m:times.map(()=>50),wind_speed_10m:times.map(()=>5),precipitation_probability:times.map(()=>0),uv_index:times.map(()=>0)}};}
const provider=()=>createOpenMeteoAdapter({days:3,clock:()=>now,fetch:async()=>Response.json(payload())});
for(const count of [2,3])test(`Compare ${count} supported weather areas with independent activity scores`,async()=>{const run=createPlanningPipeline({provider:provider(),clock:()=>now});const r=await run({mode:"compare",areaIds:["amman-central","shafa-badran","abdoun"].slice(0,count),minutes:60});assert.equal(r.rows.length,count);assert.ok(r.rows.every(r=>r.days[0].walking.score===90&&r.days[0].running.score===65));});
test("3-day adapter requests and validates all 72 real hourly slots",async()=>{let url="";const p=createOpenMeteoAdapter({days:3,clock:()=>now,fetch:async u=>{url=String(u);return Response.json(payload());}});const r=await p.getForecast({latitude:32,longitude:35.8},now);assert.ok(r.ok);assert.equal(r.hourly.length,72);assert.equal(new URL(url).searchParams.get("end_date"),"2026-09-17");const run=createPlanningPipeline({provider:p,clock:()=>now});const out=await run({mode:"outlook",areaIds:["amman-central"],minutes:90});assert.deepEqual(out.rows[0].days.map(d=>d.date),["2026-09-15","2026-09-16","2026-09-17"]);assert.ok(out.rows[0].days.every(d=>Date.parse(d.walking.bestWindow!.end)-Date.parse(d.walking.bestWindow!.start)===5400000));});
test("Map score payload contains only discrete supported points; unavailable weather stays null",async()=>{const run=createPlanningPipeline({provider:{getForecast:async()=>({ok:false,code:"network",message:"offline",retryable:true})},clock:()=>now});const r=await run({mode:"map",areaIds:["amman-central","abdoun"],minutes:30});assert.equal(r.rows.length,2);assert.equal(r.rows[0].days[0].walking.score,null);assert.equal(r.rows[0].days[0].running.score,null);assert.equal(r.rows[0].days[0].walking.bestWindow,null);});
test("Planning rejects unknown areas, coordinates, duplicates and unbounded comparisons",()=>{for(const x of [{mode:"compare",areaIds:["amman-central"]},{mode:"compare",areaIds:["amman-central","amman-central"]},{mode:"map",areaIds:["invented"]},{mode:"outlook",areaIds:["amman-central"],latitude:32},{mode:"compare",areaIds:["amman-central","abdoun","jubaiha","khalda"]}])assert.throws(()=>parsePlanningRequest({...x,minutes:60}));});
test("Planning HTTP validates origin and body before any weather calls",async()=>{let calls=0;const handler=createPlanningHandler(createPlanningPipeline({provider:{getForecast:async()=>{calls++;throw new Error();}}}));const req=(body:unknown,origin="http://localhost")=>new Request("http://localhost/api/planning",{method:"POST",headers:{origin,"content-type":"application/json"},body:JSON.stringify(body)});assert.equal((await handler(req({mode:"map",areaIds:["fake"],minutes:60}))).status,400);assert.equal((await handler(req({},"https://evil.example"))).status,403);assert.equal(calls,0);});
test("Saved areas validate supported IDs and labels, never accept exact GPS",()=>{assert.deepEqual(parseSavedAreas([]),[]);assert.deepEqual(parseSavedAreas([{areaId:"abdoun",label:" Home "}]),[{areaId:"abdoun",label:"Home"}]);for(const value of [[{areaId:"fake",label:"Work"}],[{areaId:"abdoun",label:"Home",latitude:32}],[{areaId:"abdoun",label:""}],[{areaId:"abdoun",label:"X"},{areaId:"abdoun",label:"Y"}]])assert.throws(()=>parseSavedAreas(value));});
test("Local activity answers stay local, bilingual and do not invent absent metrics",()=>{assert.equal(localActivityAnswer("weather tomorrow",[],"en",now),null);assert.match(localActivityAnswer("my activity today",[],"en",now)!,/No matching completed/);assert.match(localActivityAnswer("نشاطي اليوم",[],"ar",now)!,/لا توجد/);});
